# parameters:
# - name: DockerRegistryServiceConnection
#   type: string
#   default: '720aa1c7-4d9a-443e-9962-64a8317debf4'

variables:
  ### Pipeline Shared configurations
  - name: DockerRegistryServiceConnection
    value: 'acraksmacnaimadev'
    #value: ${{ parameters.DockerRegistryServiceConnection }}

  - name: ContainerRegistry
    value: 'acraksmacnaimadev.azurecr.io'

  - name: VmImage
    value: 'ubuntu-latest'

  ### Pipeline App Default configurations
  - name: App.DockerfilePath
    value: '$(App.SourcePath)/Dockerfile'

  - name: App.ImageRepository
    value: 'catalog-integration/$(App.Name)'

  - name: App.ImageTag
    value: '$(Build.BuildNumber)'

  - name: App.ImagePullSecret
    value: '$(App.Name)-image-pull'

  - name: App.DeploymentEnvironment_DEV
    value: 'marketplace-catalog-integration-dev.catalog-integration-dev'

  - name: App.DeploymentEnvironment_QA
    value: 'marketplace-catalog-integration-qa.catalog-integration-qa'
