apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcategorizationworker
spec:
  selector:
    matchLabels:
      app: productcategorizationworker
  revisionHistoryLimit: 2 # Default to 10 if not specified
  template:
    metadata:
      labels:
        app: productcategorizationworker # the label for the pods and the deployments
    spec:
      containers:
      - name: productcategorizationworker
        image: acraksmacnaimadev.azurecr.io/catalog-integration/productcategorizationworker:latest # IMPORTANT: update with your own repository
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # the application listens to this port
        envFrom:
          - configMapRef:
              name: sharedapps  # the name of the Kubernetes secret containing the data
          - configMapRef:
              name: productcategorizationworker # the name of the Kubernetes secret containing the data
        resources:
          requests: # minimum resources required
            cpu: 100m
            memory: 128Mi
          limits: # maximum resources allocated
            cpu: 250m
            memory: 320Mi
      #   readinessProbe: # is the container ready to receive traffic?
      #     httpGet:
      #       port: 3000
      #       path: /healthz
      #   livenessProbe: # is the container healthy?
      #     httpGet:
      #       port: 3000
      #       path: /healthz
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 1
      #       preference:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - app
